<?php

/**
 * @file
 * Module file for startupspark module.
 *
 * @link http://azbukaweb.ru/node/192 Drupal 7: С чего начать @endlink
 * @link http://azbukaweb.ru/node/194 Вставка комментариев и реализация Вашего первого хука @endlink
 * @link http://dgo.to/1354 Doxygen and comment formatting conventions @endlink
 */

// hook_menu() => hook_form() => hook_form_validate() =(success)=> hook_form_submit()
// hook_block_info() => hook_block_view()
// hook_form_alter() => hook_user_insert()

/**
 * Constant variables.
 */
// Schema prefix.
define('STARTUPSPARK_SCHEMA_PREFIX', variable_get('startupspark_schema_prefix'));
// Get the path to this module.
define('STARTUPSPARK_ROOT', drupal_get_path('module', 'startupspark'));

/**
 * Preload certain files whose functions we need at all times.
 */
//require_once dirname(__FILE__) . '/startupspark.helpers.inc';
require_once STARTUPSPARK_ROOT . '/startupspark.helpers.inc';

/**
 * Implements hook_init().
 *
 * This hook is run at the beginning of the page request.
 *
 * @link https://api.drupal.org/api/function/hook_init/7 @endlink
 * @link https://api.drupal.ru/api/function/hook_init/6 @endlink
 * @link https://drupal.stackexchange.com/a/9835 @endlink
 */
function startupspark_init() {

  // include ctools modal: http://dgo.to/1710566
  drupal_add_library('system', 'drupal.ajax');
  ctools_include('ajax');
  ctools_include('modal');
  ctools_modal_add_js();

  // drupal_add_css(), drupal_add_js() and drupal_add_library() removed in favor of #attached
  // http://dgo.to/2169605

  if (theme_exists('bootstrap')) {
    drupal_add_css(
      STARTUPSPARK_ROOT . '/css/overrides-paper.css',
      array('group' => CSS_THEME, 'every_page' => TRUE)
    );
    drupal_add_css(
      STARTUPSPARK_ROOT . '/css/custom.css',
      array('group' => CSS_THEME, 'every_page' => TRUE)
    );

    // https://api.drupal.org/api/function/module_exists/7
    if (module_exists('select2')) { // TRUE if the module is both installed and enabled
      drupal_add_css(
        STARTUPSPARK_ROOT . '/css/select2-bootstrap-paper.css',
        array('group' => CSS_THEME, 'every_page' => TRUE)
      );
      drupal_add_css(
        STARTUPSPARK_ROOT . '/css/custom-search.css',
        array('group' => CSS_THEME, 'every_page' => TRUE)
      );
    }
  }
}

/**
 * Implements hook_help().
 * Help text.
 *
 * @link https://api.drupal.org/api/function/hook_help @endlink
 * @link http://dgo.to/632280 Help text standard (for core and contrib) @endlink
 * @link http://dgo.to/604342 Guidelines for Drupal module to use when writing user interfaces text @endlink
 * @link http://dgo.to/161085#hook_help Provide help text in the Drupal UI @endlink
 * @link http://dgo.to/2181737 README Template @endlink
 * @link http://habr.ru/p/245117 @endlink
 * @link http://azbukaweb.ru/node/194 @endlink
 *
 * @param   string  $path
 *   The router menu path.
 * @param   array   $arg
 *   Array that holds the current path as returned from arg() function.
 *
 * @return  string
 */
function startupspark_help($path, $arg) {
  switch ($path) {
    // Help text for the admin section, using the module name in the path.
    case 'admin/help#startupspark':

      // Return a line-break version of the module README.txt

      // Multiple File Exists Checking? A Better way?: https://stackoverflow.com/a/4770273
      $filepath = STARTUPSPARK_ROOT . '/README';
      $list = array_filter(array("$filepath.md", "$filepath.txt"), 'file_exists');
      if ($output = array_shift($list)) {
        $output = file_get_contents($output);
      } else {
        return NULL;
      }

      if (module_exists('markdown')) {
        $info = module_invoke('markdown', 'filter_info')['filter_markdown'];
        if (function_exists($info['process callback'])) {
          //return filter_xss_admin($info['process callback']($output, NULL));
          return $info['process callback']($output, NULL);
        }
      }

      return '<pre>' . check_plain($output) . '</pre>';

    // Help for another path in the startupspark module.
    //case 'admin/build/startupspark':
    //  return '<p>' . t('') . '</p>';
  }
}

/**
 * Implements hook_menu().
 *
 * Автоматическое создание пунктов меню, табов.
 *
 * @link https://api.drupal.org/api/function/hook_menu/7 @endlink
 * @link https://api.drupal.org/api/function/user_menu/7 @endlink
 * @link https://api.drupal.org/api/function/menu_example_menu/7 @endlink
 */
function startupspark_menu() {
  $items = array();

  /**
   * Страницы настройки модуля.
   * ----------------------------------------------------------------------
   */
  $items['admin/config/content/startupspark'] = array(
    'file'             => 'startupspark.admin.inc',
    // Don't use t() for menu title and description.
    // https://api.drupal.org/api/function/hook_menu/7#comment-51103
    'title'            => 'Стартапы',
    'description'      => 'На данной странице можно настроить модуль Startups park.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('startupspark_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );


  /**
   * Список самых популярных стартапов.
   * ----------------------------------------------------------------------
   */
  // redirect to `discover/top`
  $items['discover'] = array(
    'title'            => 'Стартапы',
    'description'      => 'Обзор стартапов.',
    'page callback'    => 'drupal_goto',
    'page arguments'   => array('discover/top'),
    'access callback'  => TRUE,
  );
  // Список самых популярных стартапов.
  $items['discover/top'] = array(
    'file'             => 'startupspark.pages.inc',
    'title'            => 'Популярные',
    'menu_name'        => 'main-menu',
    'description'      => 'Ежедневно обновляемый список самых популярных стартапов.',
    'page callback'    => 'startupspark_top_page',
    'page arguments'   => array(2, 3),
    'access callback'  => TRUE,
  );
  // Вкладка популярных за всё время
  $items['discover/top/alltime'] = array(
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'title'            => 'За все время',
    'weight'           => 1,
  );
  // Страница со всеми стартапами
  $items['discover/top/alltime/all'] = array(
    'type'             => MENU_LOCAL_ACTION,
    'title'            => 'Показать все',
    //'page arguments'   => array(3),
    'access callback'  => TRUE,
  );
  // Вкладка популярных за день
  $items['discover/top/daily'] = array(
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'startupspark.pages.inc',
    'title'            => 'За день',
    'weight'           => 4, // TODO: it is assumed to add `monthly` tab (Popular This Month, За месяц)
    'page callback'    => 'startupspark_placeholder_page',
    'access callback'  => TRUE,
  );


  /**
   * Страницы управления стартапом
   * ----------------------------------------------------------------------
   */
  // Подробная информация о стартапе
  $items['projects/%startup'] = array(
    'file'             => 'startupspark.pages.inc',
    'description'      => 'Страница с основной информацией о стартапе.',
    'page callback'    => 'startupspark_project_page',
    'page arguments'   => array(1, 2),
    'access callback'  => TRUE,
  );
  // Вкладка с обзором информации о стартапе
  $items['projects/%startup/overview'] = array(
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'title'            => 'Обзор',
  );
  // Вкладка редактирования информации о стартапе
  // TODO: need to be implemented!
  $items['projects/%startup/edit'] = array(
    'type'             => MENU_LOCAL_TASK,
    'title'            => 'Редактирование',
    'access arguments' => array('access custom user tab'),
  );
  // Вкладка удаления стартапа
  // TODO: need to be implemented!
  $items['projects/%startup/delete'] = array(
    'type'             => MENU_LOCAL_TASK,
    'title'            => 'Удаление',
    'access arguments' => array('access custom user tab'),
  );


  /**
   * Добавление информации о стартапе
   * ----------------------------------------------------------------------
   */
  // Страница добавления информации о стартапе, если у данного пользователя нет добавленных
  $items['user/%/project'] = array(
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'startupspark.forms.inc',
    'title'            => 'Мой стартап',
    //'weight'           => 100,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('startupspark_add_startup_form', 1),
    'access callback'  => 'user_is_logged_in', // https://drupal.stackexchange.com/a/51184
    // https://drupal.stackexchange.com/a/95989
    //'title callback' => 'user_page_title',
    //'title arguments' => array(1),
  );


  /**
   * Регистрация/аутентификация пользователя в модальных окнах
   * ----------------------------------------------------------------------
   */
  $items['user/register/%ctools_js'] = array(
    'file'             => 'startupspark.pages.inc',
    //'plid'             => 0,
    'title'            => 'Регистрация',
    'options'          => array('attributes' => array('class' => array('ctools-use-modal'))), // important line
    'menu_name'        => 'user-menu',
    'description'      => 'Зарегистрироваться на сайте.',
    'page callback'    => 'user_menu_modal_callback',
    'page arguments'   => array(1, 2),
    // Hide a menu item for anonymous user: http://dgo.to/1421926#comment-8440561
    'access callback'  => 'user_is_anonymous',
  );
  $items['user/login/%ctools_js'] = array(
    'file'             => 'startupspark.pages.inc',
    'title'            => 'Вход',
    'weight'           => 1,
    'options'          => array('attributes' => array('class' => array('ctools-use-modal'))),
    'menu_name'        => 'user-menu',
    'description'      => 'Войти на сайт.',
    'page callback'    => 'user_menu_modal_callback',
    'page arguments'   => array(1, 2),
    'access callback'  => 'user_is_anonymous',
  );


  /**
   * Страница поиска стартапов
   * ----------------------------------------------------------------------
   */
  $items['search/projects'] = array(
    'file'             => 'startupspark.forms.inc',
    'title'            => 'Поиск стартапов',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('form_search_projects'),
    'access callback'  => TRUE,
  );
  // path with autocomplete function for projects
  // The important thing to note here is that the custom autocomplete
  // variable you’re passing via the URL is appearing first here,
  // BEFORE the standard autocomplete text argument.
  // http://complexdan.com?p=43
  $items['search/projects/autocomplete/%'] = array(
    'type'             => MENU_CALLBACK, // https://drupal.stackexchange.com/a/81830
    'file'             => 'startupspark.pages.inc',
    'page callback'    => 'json_list_projects',
    'page arguments'   => array(3),
    'access callback'  => TRUE,
  );

  return $items;
}

/**
 * Implements hook_menu_link_alter().
 *
 * @link https://drupal.stackexchange.com/a/4949 @endlink
 */
function startupspark_menu_link_alter(&$item) {
  // TODO: replace it with other more accurate solution.
  //if('example_test_modal_callback' === $item['page callback']) {}
  switch($item['link_path']) {
    case 'user/register/%':
    case 'user/login/%':
    //case 'discover/top':

      // Check if already created.
      $mlid = db_select('menu_links', 'ml')
        ->fields('ml', array('mlid'))
        ->condition('ml.link_path', $item['link_path'])
        ->execute()
        ->fetchField();

      if(!empty($mlid)) {
        // The menu link ID (mlid) is the integer primary key.
        $item['mlid'] = $mlid;
      }

      // The parent link ID (plid) is the mlid of the link above in the hierarchy,
      // or zero if the link is at the top level in its menu.
      $item['plid'] = 0;

      // A flag to indicate that the user has manually created or edited the link
      // (1 = customized, 0 = not customized).
      $item['customized'] = 1;

      // The name of the module that generated this link.
      $item['module'] = 'startupspark';

      // The depth relative to the top level. A link with plid == 0 will have depth == 1.
      //$item['depth'] = 1;

      break;
  }
}

function form_search_projects_block($form, &$form_state) {

  $query = db_select(STARTUPSPARK_SCHEMA_PREFIX . 'startup');
  $query->addExpression('MIN(staff_count)');
  $query->addExpression('MAX(staff_count)');

  list($min, $max) = array_pad(array_values($query->execute()->fetchAssoc()), 2, 10);

  $range = '[' . $min . ',' . $max . ']';

  $form['fieldset1'] = array(
    '#type' => 'fieldset',
    '#title' => 'По количеству участников',
    //'#weight' => 5,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#states' => array(
      'collapsed' => array(
        ':input[name="keyword"]' => array('empty' => FALSE),
      ),
    ),
  );

  $form['fieldset1']['rangefield'] = array(
    //'#id' => 'rangefield',
    '#type' => 'textfield',
    '#prefix' => '<p class="control-label" for="rangefield">Диапазон:</p><br>',
    '#default_value' => 1,
    // https://github.com/seiyria/bootstrap-slider
    '#attributes'    => array(
      'data-slider-min'  => $min,
      'data-slider-max'  => $max,
      'data-slider-value'  => $range,
      'data-slider-range'  => TRUE,
      'data-slider-ticks'  => $range,
      'data-slider-ticks-labels'  => '["От ' . $min . '", "До ' . $max . '"]',
      'data-slider-tooltip-split' => TRUE,
    ),
    '#attached' => array(
      'css' => array(
        array(
          'data'  => 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/css/bootstrap-slider.min.css',
          'type'  => 'external',
          'group' => CSS_THEME,
        ),
        array(
          'data'  => '.slider-selection{background:#d099d9}.slider.slider-horizontal{width:90%;margin-left:10px}',
          'type'  => 'inline',
          'group' => CSS_THEME,
        ),
      ),
      'js' => array(
        array(
          'data'  => 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/bootstrap-slider.min.js',
          'type'  => 'external',
          'scope' => 'header',
        ),
        array(
          'data'  => STARTUPSPARK_ROOT . '/js/slider.js',
          'scope' => 'footer',
        ),
      ),
    ),
  );

  $form['fieldset1']['submit'] = array(
    '#type'  => 'submit',
    '#value' => 'Найти',
  );

  $form['fieldset2'] = array(
    '#type' => 'fieldset',
    '#title' => 'По роду деятельности',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  // Autocomplete field
  $form['fieldset2']['keyword'] = array(
    '#type'              => 'textfield',
    '#size'              => 30,
    '#title'             => 'Род деятельности',
    '#attributes'        => array('placeholder' => array('Например, спорт')),
    '#description'       => 'Введите ключевое слово.',
    '#autocomplete_path' => 'search/projects/autocomplete/category',
  );

  $form['fieldset2']['submit'] = array(
    '#type'  => 'submit',
    '#value' => 'Найти',
  );

  return $form;
}

/**
 * Drupal form submit handler.
 */
function form_search_projects_block_submit($form, &$form_state) {

  // TODO: creates problems on concurrent requests!
  if(!empty($form_state['values']['keyword'])) {
    cache_set('search-keyword', $form_state['values']['keyword'], 'cache');
  }

  drupal_goto('search/projects');
}

/**
 * Implements hook_block_info().
 *
 * @link https://api.drupal.org/api/function/hook_block_info/7 @endlink
 */
function startupspark_block_info() {
  $blocks['startup_filter'] = array(
    'info'   => 'Filter of startups',
    // https://api.drupal.org/api/drupal/includes!common.inc/group/block_caching/7
    'cache'  => DRUPAL_NO_CACHE,
    'status' => 1,
    'region' => 'sidebar_first',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function startupspark_block_view($delta = '') {
  switch ($delta) {
    case 'startup_filter':

      $block['title'] = 'Фильтр';

      // Prevent strict warning: "Only variables should be passed by reference".
      // https://drupal.stackexchange.com/q/60411
      $form = drupal_get_form('form_search_projects_block');

      // Using this technique, you can encapsulate the js and css loading in your module_block_view
      // https://api.drupal.org/api/function/hook_block_info/7#comment-50868
      // https://api.drupal.org/api/function/drupal_add_css/7#comment-53463
      $block['content'] = array(
        '#markup' => drupal_render($form),
        '#attached' => array('css' => array(STARTUPSPARK_ROOT . '/css/custom.css')),
      );

      return $block;
  }
}

/**
 * Implements hook_load().
 *
 * @link http://drupalace.ru/node/346 @endlink
 */
function startup_load($arg) {

  // TODO: proper fetch from cache if exist

  if ($cache = cache_get($arg)) {
    return $cache->data;
  }

  // you must pass a STRING to ctype_digit function: http://php.net/ctype-digit#112040
  $is_id = ctype_digit((string)$arg);

  // fetch() should generally be avoided in favor of fetchObject() and fetchAssoc(),
  // as the latter are more self-documenting.
  // http://dgo.to/1251174
  $startup = db_select(STARTUPSPARK_SCHEMA_PREFIX . 'startup', 's')
    ->fields('s')
    ->condition($is_id ? 's.id' : 's.name', $arg)
    ->range(0, 1) // get only one result: http://drupal.stackexchange.com/a/166593
    ->execute()
    ->fetchObject();

  if (empty($startup)) {
    // 404

    // Note that a load function should return FALSE when it is unable to provide a loadable object.
    // The menu routing system will return a 404 error in this case.
    // https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_menu/7
    return FALSE;
  }
  if ($is_id) {
    // redirect: `projects/%id` (short link) => `projects/%name` (main page)

    // TODO: need to cache this value to prevent extra queries to db
    cache_set($startup->name, $startup, 'cache');
    drupal_set_message('Вы были перенаправлены на основную страницу стартапа.');
    drupal_goto('projects/' . $startup->name);
  }
  return $startup;
}


/**
 * Implements hook_form_alter().
 *
 * Сurrently Drupal runs hook_form_alter AFTER hook_form_FORM_ID_alter.
 * Some say it is safest to use hook_form_alter and a switch statement.
 * https://stackoverflow.com/q/2264301#comment2351220_2302029
 *
 * @link https://github.com/aramboyajyan/drupal7-boilerplate @endlink
 * @link https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7 @endlink
 */
function startupspark_form_alter(&$form, &$form_state, $form_id) {

  /**
   * General overrides.
   */
  switch ($form['#id']) {

    // User login form.
    //case 'user-login':
    //  break;

    // User registration form.
    case 'user-register-form':
    //case 'user-register-form--2': // TODO: choose way to prevent possible dublicates
      $form['account']['name']['#weight'] = 0;

      // TODO: need to delete from release
      form_set_error('mail', 'В данный момент в azure пока не настроена оправка e-mail.');
      unset($form['account']['mail']['#description']);

      $form['account']['label_main'] = array(
        '#markup' => '<h3>Заполните учётные данные.</h3>',
        '#weight'        => -1,
      );
      $form['account']['pass'] = array(
        '#type'          => 'password_confirm',
        '#required'      => TRUE,
        // We need to remove the label to get a nice version: https://wp.me/p3PJLY-gP
        '#title_display' => 'invisible',
      );

      // Add a checkbox to registration form about agreeing to terms of use.
      // https://api.drupal.org/api/function/hook_form_FORM_ID_alter/7
      $form['account']['terms_of_use'] = array(
        '#type'          => 'checkbox',
        // I agree with the website's terms and conditions.
        //t('I certify that I am over the age of 18 years old.'),
        '#title'         => 'Я подтверждаю, что мне больше 18 лет.',
        '#required'      => TRUE,
      );
      // Drupal 7 FAPI - Using form states for conditional field display: http://knackforge.com/node/77
      // how to change value of submit button of comment form? https://drupal.stackexchange.com/a/40563
      $form['actions']['submit']['#states'] = array(
        'enabled' => array(
          ':input[name="terms_of_use"]' => array('checked' => TRUE),
        ),
      );
      $form['actions']['submit']['#attributes'] = array('class' => array('btn-primary'));

      break;
  }

  /**
   * Specific overrides.
   */
  switch ($form_id) {

    // Add missing bootstrap classes and role to search form.
    // Темизация элементов формы поиска в Dpupal 7: http://master-web.info?p=3733
    // TODO: you should change access to search box on `admin/people/permissions` page for non-admin users
    // Search block not visible: http://dgo.to/1092502
    case 'search_block_form':

      $form['search_block_form']['#title_display'] = 'invisible'; // Toggle label visibilty
      $form['search_block_form']['#attributes']['class'][] = 'form-control';
      if (module_exists('select2')) {
        $form['search_block_form']['#attributes']['class'][] = 'hidden';
      }
      $form['#attributes']['class'] = array('navbar-form');

      if (module_exists('select2')) {
        require_once DRUPAL_ROOT . '/includes/locale.inc'; // Necessary for country_get_list().
        $select2 = array(
          '#type' => 'select',
          '#title' => 'Выберите страну (Select2 example)',

          // If returned values are identical to displayed values, you can use drupal_map_assoc()
          // https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7#options
          '#options' => drupal_map_assoc(country_get_list()),
          '#empty_option' => 'Выберите страну',
          // https://select2.github.io/select2/#documentation
          // https://select2.github.io/select2/#infinite
          '#select2' => array(
            'width' => '100%',
            'allowClear' => FALSE, // display clear button
            'placeholder' => 'Введите название',
            'dropdownCssClass' => 'bigdrop', // apply css that makes the dropdown taller
            'minimumInputLength' => 1,
            'maximumInputLength' => 10,
            'maximumSelectionSize' => 3,
          ),
        );

        // https://php.net/array-merge
        $form['search_block_form'] = array_merge($form['search_block_form'], $select2);
      }

      break;
  }
}


/**
 * Implements hook_theme().
 *
 * @link https://stackoverflow.com/a/8258798 @endlink
 * @link https://github.com/aramboyajyan/drupal7-boilerplate/blob/master/boilerplate.module#L415 @endlink
 */
function startupspark_theme($existing, $type, $theme, $path) {
  // Define theme dir.
  $theme_dir   = STARTUPSPARK_ROOT . '/theme';

  // Themable elements. Theme keys.
  return array(
    'startupspark-overview' => array(
      // path to your template file
      'path'      => $theme_dir,
      // your template filename
      'template'  => 'overview', // do not include .tpl.php
      'variables' => array(
        'startup' => NULL,
        'staff'   => NULL,
      ),
    ),
    'startupspark-discover' => array(
      'path'      => $theme_dir,
      'template'  => 'discover',
      'variables' => array(
        'title'   => NULL,
        'content' => NULL
      ),
    ),
    'startupspark-list' => array(
      'path'      => $theme_dir,
      'template'  => 'list',
      'variables' => array(
        'title'   => NULL,
        'content' => NULL
      ),
    ),
  );
}
